#! /bin/sh -e
# preinst script for moodle 

get_config() {
    db_get moodle/webserver
    webserver="$RET"
}

uninclude() {
	. /usr/share/debconf/confmodule
	db_version 2.0

	# Read debconf and edit the config file accordingly
	get_config
	db_stop
	exec 0<&1

	# Remove include from httpd.conf when upgrading from older versions
	if [ ! -f /etc/${webserver}/conf.d/moodle ]; then
		if [ -f /etc/${webserver}/httpd.conf \
			-a -f /usr/share/wwwconfig-common/apache-uninclude_all.sh ]
		then
			includefile=/etc/moodle/apache.conf
			server="${webserver}"
			servers="apache apache-ssl apache-perl apache2"
			. /usr/share/wwwconfig-common/apache-uninclude_all.sh
		fi
	fi
}

case "$1" in
	upgrade)
		#remove old sessions when upgrading from < than 1.4.4-1
		if dpkg --compare-versions "$2" lt "1.4.4-1"; then
			find /var/lib/moodle/sessions -type f -print0 | xargs -r0 rm -f
		fi

	 	uninclude
		;;
	install)
		# if the package was not purged we are called with the version
		# as second paramter
		if [ $# -eq 2 ]
		then
			uninclude
		fi
		;;
esac

#DEBHELPER#

exit 0
